translation_api_url: 'http://127.0.0.1:5000/translate'
rag_api_url: 'http://localhost:8000/ask'
hsbc_image_url: 'https://www.hsbc.co.in/content/dam/hsbc/in/images/01_HSBC_MASTERBRAND_LOGO_RGB.svg'
languages:
  English: 'en'
  Hindi: 'hi'
  Bengali: 'bn'
  Telugu: 'te'
  Marathi: 'mr'
  Tamil: 'ta'
  Gujarati: 'gu'
  Kannada: 'kn'
  Malayalam: 'ml'
  Punjabi: 'pa'
